Failed to convert dandiset 001364: 
Failed to open NWB file from URL https://dandiarchive.s3.amazonaws.com/blobs/867/3be/8673be13-ab99-4b7b-a5c3-fb5a7d03ea19: Unable to synchronously open file (file signature not found)

Possible that backend is not supported.
Please raise an issue on https://github.com/con/nwb2bids/issues/new to discuss.

Traceback:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/nwb2bids/bids_models/_bids_microephys_session_metadata.py", line 94, in _stream_nwb
    h5py_file = h5py.File(name=rem_file, mode="r")
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/h5py/_hl/files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/h5py/_hl/files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/nwb2bids-dandisets-dashboard/nwb2bids-dandisets-dashboard/scripts/run_nwb2bids_on_dandisets.py", line 30, in <module>
    dataset_converter.extract_metadata()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/nwb2bids/_converters/_dataset_converter.py", line 135, in extract_metadata
    collections.deque(
    ~~~~~~~~~~~~~~~~~^
        (
        ^
    ...<4 lines>...
        maxlen=0,
        ^^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/nwb2bids/_converters/_dataset_converter.py", line 137, in <genexpr>
    session_converter.extract_metadata()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/nwb2bids/_converters/_session_converter.py", line 74, in extract_metadata
    self.session_metadata = BidsSessionMetadata.from_nwbfile_paths(nwbfile_paths=self.nwbfile_paths)
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/pydantic/_internal/_validate_call.py", line 39, in wrapper_function
    return wrapper(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/pydantic/_internal/_validate_call.py", line 136, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/nwb2bids/bids_models/_bids_microephys_session_metadata.py", line 44, in from_nwbfile_paths
    nwbfiles = [_stream_nwb(url=url) for url in nwbfile_paths]
                ~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/nwb2bids/bids_models/_bids_microephys_session_metadata.py", line 101, in _stream_nwb
    raise ValueError(message)
ValueError: 
Failed to open NWB file from URL https://dandiarchive.s3.amazonaws.com/blobs/867/3be/8673be13-ab99-4b7b-a5c3-fb5a7d03ea19: Unable to synchronously open file (file signature not found)

Possible that backend is not supported.
Please raise an issue on https://github.com/con/nwb2bids/issues/new to discuss.
